apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2-deployment
  labels:
    app: nginx2
spec:
  replicas: 3 # Specifies that Kubernetes should maintain 3 replicas of this pod
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:1.28.0 # Uses the latest Nginx official image from Docker Hub
        ports:
        - containerPort: 80 # Exposes port 80 for the Nginx web server
        resources:
          limits:
            cpu: "500m" # Requests 0.5 CPU core
            memory: "128Mi" # Requests 128 MiB of memory
          requests:
            cpu: "250m" # Limits to 0.5 CPU core
            memory: "64Mi" # Limits to 128 MiB of memory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2-service
spec:
  selector:
    app: nginx2 # Selects pods with the label 'app: nginx'
  type: NodePort # Defines the service type as NodePort
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on (inside the cluster)
      targetPort: 80 # The port on the pod that the service will forward traffic to
      nodePort: 30080 # Optional: You can specify a specific NodePort, typically in the range 30000-32767. If not specified, Kubernetes will assign one.