apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-registry-deployment
  labels:
    app: harbor-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-registry
  template:
    metadata:
      labels:
        app: harbor-registry
    spec:
      containers:
      - name: harbor-registry
        image: goharbor/harbor-registry:v2.10.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-pvc