apiVersion: v1
kind: Service
metadata:
  name: harbor-registry-service
  labels:
    app: harbor-registry
spec:
  selector:
    app: harbor-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
