apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3 # Você pode ajustar o número de réplicas conforme sua necessidade
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.28.0 # Usaremos a imagem mais recente do Nginx
        ports:
        - containerPort: 80 # A porta padrão do Nginx