apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 3 # Define o número de réplicas do Pod
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest # Imagem oficial do Apache HTTP Server
        ports:
        - containerPort: 80 # Porta padrão do Apache
      tolerations: # <--- NOVA SEÇÃO ADICIONADA AQUI
      - key: "hardware"
        operator: "Equal"
        value: "high"
        effect: "NoSchedule"