apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10 # Define o número de réplicas do Pod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:,,,,,,,,,,,,,,,,,,, # Imagem oficial do Nginx
        ports:
        - containerPort: 80 # Porta padrão do Nginx